name: Standard Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  call-standard-test:
    name: Test
    uses: gobuffalo2/.github/.github/workflows/go-test.yml@v1.4
    secrets: inherit
